---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myxara/public_html/invoice
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    #    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/invoice
    - /bin/cp ./public/js/*.js $DEPLOYPATH
    - /bin/cp ./public/css/*.css $DEPLOYPATH